<a href="https://colab.research.google.com/github/ragavkish/a.n.d.r.e.w./blob/main/train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://raw.githubusercontent.com/ragavkish/a.n.d.r.e.w./refs/heads/main/input.txt

--2024-12-23 06:23:55--  https://raw.githubusercontent.com/ragavkish/a.n.d.r.e.w./refs/heads/main/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2896107 (2.8M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   2.76M  --.-KB/s    in 0.03s   

2024-12-23 06:23:56 (92.5 MB/s) - ‘input.txt’ saved [2896107/2896107]



In [ ]:
with open('input.txt', 'r', encoding = 'utf-8') as f:
  text = f.read()

In [ ]:
print("length of characters: ", len(text))

length of characters:  2864550


In [ ]:
print(text[:5000])

GOD CREATED
THE INTEGERS

GOD CREATED THE INTEGERS
THE MATHEMATICAL BREAKTHROUGHS THAT CHANGED HISTORY

EDITED, WITH COMMENTARY, BY

STEPHEN
HAWKING

RUNNING PRESS
PHILADELPHIA • LONDON
CONTENTS
Introduction

EUCLID
(C. 325BC–265BC)
His Life and Work
Selections from Euclid’s Elements
Book I: Basic Geometry—Definitions, Postulates, Common Notions; and
Proposition 47, (leading up to the Pythagorean Theorem)
Book V: The Eudoxian Theory of Proportion—Definitions & Propositions
Book VII: Elementary Number Theory—Definitions & Propositions
Book IX: Proposition 20: The Infinitude of Prime Numbers
Book IX: Proposition 36: Even Perfect Numbers
Book X: Commensurable and Incommensurable Magnitudes

ARCHIMEDES
(287BC–212BC)
His Life and Work
Selections from The Works of Archimedes
On the Sphere and Cylinder, Books I and II
Measurement of a Circle
The Sand Reckoner
The Methods

DIOPHANTUS
(C. 200–284)
His Life and Work
Selections from Diophantus of Alexandria, A Study in the History of Greek
Alg

In [ ]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_abcdefghijklmnopqrstuvwxyz{|}~£§¯°±µ·½ÁÈÉÖ×Üàáâäæçèéêëîïòóôö÷üĀāīŒœŚşŨūƒəʅΓΔΘΙΛΞΠΣΦΨΩέΰαβγδεζηθκλμνξοπρςστυφχψωύϕϵ–—‘’“”‡•…′″‴Ω⅓→↔∊∏∑−∓∞∠∥∫∴≅≠≡≤≥⊢⊥
208


In [ ]:
# prompt: mapping from characters to integers

stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

print(encode("hii there"))
print(decode(encode("hii there")))

[68, 69, 69, 2, 80, 68, 65, 78, 65]
hii there


In [ ]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([2864550]) torch.int64
tensor([  1,  38,  46,  35,   2,  34,  49,  36,  32,  51,  36,  35,   0,  51,
         39,  36,   2,  40,  45,  51,  36,  38,  36,  49,  50,   0,   0,   1,
         38,  46,  35,   2,  34,  49,  36,  32,  51,  36,  35,   2,  51,  39,
         36,   2,  40,  45,  51,  36,  38,  36,  49,  50,   0,  51,  39,  36,
          2,  44,  32,  51,  39,  36,  44,  32,  51,  40,  34,  32,  43,   2,
         33,  49,  36,  32,  42,  51,  39,  49,  46,  52,  38,  39,  50,   2,
         51,  39,  32,  51,   2,  34,  39,  32,  45,  38,  36,  35,   2,  39,
         40,  50,  51,  46,  49,  56,   0,   0,  36,  35,  40,  51,  36,  35,
         11,   2,  54,  40,  51,  39,   2,  34,  46,  44,  44,  36,  45,  51,
         32,  49,  56,  11,   2,  33,  56,   0,   0,  50,  51,  36,  47,  39,
         36,  45,   0,  39,  32,  54,  42,  40,  45,  38,   0,   0,  49,  52,
         45,  45,  40,  45,  38,   2,  47,  49,  36,  50,  50,   0,  47,  39,
         40,  43,  32,  35,  3

In [ ]:
n=int(0.9*len(data))
train = data[:n]
val = data[n:]

In [ ]:
block_size = 8
train[:block_size+1]

tensor([ 1, 38, 46, 35,  2, 34, 49, 36, 32])

In [ ]:
x = train[:block_size]
y = train[1:block_size+1]
for t in range(block_size):
  context = x[:t+1]
  target = y[t]
  print(f"when input is {context} the target: {target}")

when input is tensor([1]) the target: 38
when input is tensor([ 1, 38]) the target: 46
when input is tensor([ 1, 38, 46]) the target: 35
when input is tensor([ 1, 38, 46, 35]) the target: 2
when input is tensor([ 1, 38, 46, 35,  2]) the target: 34
when input is tensor([ 1, 38, 46, 35,  2, 34]) the target: 49
when input is tensor([ 1, 38, 46, 35,  2, 34, 49]) the target: 36
when input is tensor([ 1, 38, 46, 35,  2, 34, 49, 36]) the target: 32


In [ ]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
  data = train if split == 'train' else val
  ix = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size):
  for t in range(block_size):
    context = xb[b, :t+1]
    target = yb[b,t]
    print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[83, 68, 65, 74,  2, 80, 68, 65],
        [81, 72, 80, 69, 65, 79, 11,  2],
        [68, 65,  0, 80, 78, 61, 74, 79],
        [69, 74, 65, 79,  2, 61, 79,  2]])
targets:
torch.Size([4, 8])
tensor([[68, 65, 74,  2, 80, 68, 65, 69],
        [72, 80, 69, 65, 79, 11,  2, 75],
        [65,  0, 80, 78, 61, 74, 79, 66],
        [74, 65, 79,  2, 61, 79,  2, 47]])
----
when input is [83] the target: 68
when input is [83, 68] the target: 65
when input is [83, 68, 65] the target: 74
when input is [83, 68, 65, 74] the target: 2
when input is [83, 68, 65, 74, 2] the target: 80
when input is [83, 68, 65, 74, 2, 80] the target: 68
when input is [83, 68, 65, 74, 2, 80, 68] the target: 65
when input is [83, 68, 65, 74, 2, 80, 68, 65] the target: 69
when input is [81] the target: 72
when input is [81, 72] the target: 80
when input is [81, 72, 80] the target: 69
when input is [81, 72, 80, 69] the target: 65
when input is [81, 72, 80, 69, 65] the target: 79
when input is

In [ ]:
print(xb)

tensor([[83, 68, 65, 74,  2, 80, 68, 65],
        [81, 72, 80, 69, 65, 79, 11,  2],
        [68, 65,  0, 80, 78, 61, 74, 79],
        [69, 74, 65, 79,  2, 61, 79,  2]])


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

  def forward(self, idx, targets=None):

    logits = self.token_embedding_table(idx)

    if targets is None:
      loss = None
    else:
      B, T, C = logits.shape
      logits = logits.view(B*T, C)
      targets =  targets.view(B*T)
      loss = F.cross_entropy(logits, targets)

    return logits, loss

  def generate(self, idx, max_new_tokens):
    for _ in range(max_new_tokens):
      logits, loss = self(idx)
      logits = logits[:, -1, :]
      probs = F.softmax(logits, dim=-1)
      idx_next = torch.multinomial(probs, num_samples=1)
      idx = torch.cat((idx, idx_next), dim=1)
    return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)


print(decode(m.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 208])
tensor(5.8508, grad_fn=<NllLossBackward0>)

Wjp¯ρ∞ξγ…ʅ“É 9GçMσ′ύàʅχεcχ×|tAΩΩ[Ö;ωæ°±−bü0ληəÜʅχÈ⊢Ām‘Éε≠ZCJîï435Ξψπ>ü’Ιδ…pvΰΨβüYρ∥a4±$µ%*Π%ερæîj£c


In [ ]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(10000):

  xb, yb = get_batch('train')

  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

print(loss.item())

2.478816270828247


In [ ]:
print(decode(m.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=500)[0].tolist()))



chistheimeng d s emers istithenif and G(bery l tofongrth br + α). bu = st the tand whingreo gion
on e, of ive isinanatond tr . E an F th
athe whondinjuas to f 0
rsubll acondumeth x,” X TR o x.
Se. an, fithereives TE an isavach isw CAR ruathys 1.
tof y to tathibes me wheexprmeamay tlome
as f te f

l th wof m, tong riodusthego t ont thar theconereime s, pon ichin m chetodishin im, as lo the plimathe 81):
catofore elag − st
respollle
vectar at,
cangrisord co alere it
Sunofin oreden d ithe des beme


In [ ]:
torch.manual_seed(1337)
B,T,C = 4,8,2
x = torch.randn(B,T,C)
x.shape


torch.Size([4, 8, 2])

In [ ]:
xbow = torch.zeros((B,T,C))
for b in range(B):
  for t in range(T):
    xprev = x[b,:t+1]
    xbow[b,t] = torch.mean(xprev, 0)

In [ ]:
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x
torch.allclose(xbow, xbow2)

False

In [ ]:
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
wei = wei / wei.sum(1, keepdim=True)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

False

In [ ]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b

print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
torch.manual_seed(1337)
B,T,C = 4,8,32
x = torch.randn(B,T,C)

head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)
q = query(x)
wei = q @ k.transpose(-2, -1)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)


tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1)


tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d:

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    xmean = x.mean(1, keepdim=True)
    xvar = x.var(1, keepdim=True)
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps)
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100)
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std()

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std()

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

batch_size = 16
block_size = 32
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0

torch.manual_seed(1337)

!wget https://raw.githubusercontent.com/ragavkish/a.n.d.r.e.w./refs/heads/main/input.txt

with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

chars = sorted(list(set(text)))
vocab_size = len(chars)

stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)
        q = self.query(x)

        wei = q @ k.transpose(-2,-1) * C**-0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        v = self.value(x)
        out = wei @ v
        return out

class MultiHeadAttention(nn.Module):

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):

    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_emb + pos_emb
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:]
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    xb, yb = get_batch('train')

    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

--2024-12-23 17:27:28--  https://raw.githubusercontent.com/ragavkish/a.n.d.r.e.w./refs/heads/main/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2896107 (2.8M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   2.76M  9.45MB/s    in 0.3s    

2024-12-23 17:27:30 (9.45 MB/s) - ‘input.txt’ saved [2896107/2896107]

0.228176 M parameters
step 0: train loss 5.4793, val loss 5.4867
step 100: train loss 2.7636, val loss 2.8598
step 200: train loss 2.6099, val loss 2.7053
step 300: train loss 2.5170, val loss 2.6157
step 400: train loss 2.4331, val loss 2.5370
step 500: train loss 2.3580, val loss 2.4780
step 600: train loss 2.2725, val loss 2.3991
step 700: train loss 2.2050, val loss 2.3529
step 800: train loss 2.1377,