<a href="https://colab.research.google.com/github/ragavkish/a.n.d.r.e.w./blob/main/train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://raw.githubusercontent.com/ragavkish/a.n.d.r.e.w./refs/heads/main/input.txt

--2024-12-23 06:23:55--  https://raw.githubusercontent.com/ragavkish/a.n.d.r.e.w./refs/heads/main/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2896107 (2.8M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   2.76M  --.-KB/s    in 0.03s   

2024-12-23 06:23:56 (92.5 MB/s) - ‘input.txt’ saved [2896107/2896107]



In [6]:
with open('input.txt', 'r', encoding = 'utf-8') as f:
  text = f.read()

In [7]:
print("length of characters: ", len(text))

length of characters:  2864550


In [9]:
print(text[:5000])

GOD CREATED
THE INTEGERS

GOD CREATED THE INTEGERS
THE MATHEMATICAL BREAKTHROUGHS THAT CHANGED HISTORY

EDITED, WITH COMMENTARY, BY

STEPHEN
HAWKING

RUNNING PRESS
PHILADELPHIA • LONDON
CONTENTS
Introduction

EUCLID
(C. 325BC–265BC)
His Life and Work
Selections from Euclid’s Elements
Book I: Basic Geometry—Definitions, Postulates, Common Notions; and
Proposition 47, (leading up to the Pythagorean Theorem)
Book V: The Eudoxian Theory of Proportion—Definitions & Propositions
Book VII: Elementary Number Theory—Definitions & Propositions
Book IX: Proposition 20: The Infinitude of Prime Numbers
Book IX: Proposition 36: Even Perfect Numbers
Book X: Commensurable and Incommensurable Magnitudes

ARCHIMEDES
(287BC–212BC)
His Life and Work
Selections from The Works of Archimedes
On the Sphere and Cylinder, Books I and II
Measurement of a Circle
The Sand Reckoner
The Methods

DIOPHANTUS
(C. 200–284)
His Life and Work
Selections from Diophantus of Alexandria, A Study in the History of Greek
Alg

In [10]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_abcdefghijklmnopqrstuvwxyz{|}~£§¯°±µ·½ÁÈÉÖ×Üàáâäæçèéêëîïòóôö÷üĀāīŒœŚşŨūƒəʅΓΔΘΙΛΞΠΣΦΨΩέΰαβγδεζηθκλμνξοπρςστυφχψωύϕϵ–—‘’“”‡•…′″‴Ω⅓→↔∊∏∑−∓∞∠∥∫∴≅≠≡≤≥⊢⊥
208


In [11]:
# prompt: mapping from characters to integers

stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

print(encode("hii there"))
print(decode(encode("hii there")))

[68, 69, 69, 2, 80, 68, 65, 78, 65]
hii there


In [16]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([2864550]) torch.int64
tensor([  1,  38,  46,  35,   2,  34,  49,  36,  32,  51,  36,  35,   0,  51,
         39,  36,   2,  40,  45,  51,  36,  38,  36,  49,  50,   0,   0,   1,
         38,  46,  35,   2,  34,  49,  36,  32,  51,  36,  35,   2,  51,  39,
         36,   2,  40,  45,  51,  36,  38,  36,  49,  50,   0,  51,  39,  36,
          2,  44,  32,  51,  39,  36,  44,  32,  51,  40,  34,  32,  43,   2,
         33,  49,  36,  32,  42,  51,  39,  49,  46,  52,  38,  39,  50,   2,
         51,  39,  32,  51,   2,  34,  39,  32,  45,  38,  36,  35,   2,  39,
         40,  50,  51,  46,  49,  56,   0,   0,  36,  35,  40,  51,  36,  35,
         11,   2,  54,  40,  51,  39,   2,  34,  46,  44,  44,  36,  45,  51,
         32,  49,  56,  11,   2,  33,  56,   0,   0,  50,  51,  36,  47,  39,
         36,  45,   0,  39,  32,  54,  42,  40,  45,  38,   0,   0,  49,  52,
         45,  45,  40,  45,  38,   2,  47,  49,  36,  50,  50,   0,  47,  39,
         40,  43,  32,  35,  3

In [17]:
n=int(0.9*len(data))
train = data[:n]
val = data[n:]

In [25]:
block_size = 8
train[:block_size+1]

tensor([ 1, 38, 46, 35,  2, 34, 49, 36, 32])

In [26]:
x = train[:block_size]
y = train[1:block_size+1]
for t in range(block_size):
  context = x[:t+1]
  target = y[t]
  print(f"when input is {context} the target: {target}")

when input is tensor([1]) the target: 38
when input is tensor([ 1, 38]) the target: 46
when input is tensor([ 1, 38, 46]) the target: 35
when input is tensor([ 1, 38, 46, 35]) the target: 2
when input is tensor([ 1, 38, 46, 35,  2]) the target: 34
when input is tensor([ 1, 38, 46, 35,  2, 34]) the target: 49
when input is tensor([ 1, 38, 46, 35,  2, 34, 49]) the target: 36
when input is tensor([ 1, 38, 46, 35,  2, 34, 49, 36]) the target: 32


In [27]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
  data = train if split == 'train' else val
  ix = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size):
  for t in range(block_size):
    context = xb[b, :t+1]
    target = yb[b,t]
    print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[83, 68, 65, 74,  2, 80, 68, 65],
        [81, 72, 80, 69, 65, 79, 11,  2],
        [68, 65,  0, 80, 78, 61, 74, 79],
        [69, 74, 65, 79,  2, 61, 79,  2]])
targets:
torch.Size([4, 8])
tensor([[68, 65, 74,  2, 80, 68, 65, 69],
        [72, 80, 69, 65, 79, 11,  2, 75],
        [65,  0, 80, 78, 61, 74, 79, 66],
        [74, 65, 79,  2, 61, 79,  2, 47]])
----
when input is [83] the target: 68
when input is [83, 68] the target: 65
when input is [83, 68, 65] the target: 74
when input is [83, 68, 65, 74] the target: 2
when input is [83, 68, 65, 74, 2] the target: 80
when input is [83, 68, 65, 74, 2, 80] the target: 68
when input is [83, 68, 65, 74, 2, 80, 68] the target: 65
when input is [83, 68, 65, 74, 2, 80, 68, 65] the target: 69
when input is [81] the target: 72
when input is [81, 72] the target: 80
when input is [81, 72, 80] the target: 69
when input is [81, 72, 80, 69] the target: 65
when input is [81, 72, 80, 69, 65] the target: 79
when input is

In [28]:
print(xb)

tensor([[83, 68, 65, 74,  2, 80, 68, 65],
        [81, 72, 80, 69, 65, 79, 11,  2],
        [68, 65,  0, 80, 78, 61, 74, 79],
        [69, 74, 65, 79,  2, 61, 79,  2]])


In [33]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

  def forward(self, idx, targets=None):

    logits = self.token_embedding_table(idx)

    if targets is None:
      loss = None
    else:
      B, T, C = logits.shape
      logits = logits.view(B*T, C)
      targets =  targets.view(B*T)
      loss = F.cross_entropy(logits, targets)

    return logits, loss

  def generate(self, idx, max_new_tokens):
    for _ in range(max_new_tokens):
      logits, loss = self(idx)
      logits = logits[:, -1, :]
      probs = F.softmax(logits, dim=-1)
      idx_next = torch.multinomial(probs, num_samples=1)
      idx = torch.cat((idx, idx_next), dim=1)
    return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)


print(decode(m.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 208])
tensor(5.8508, grad_fn=<NllLossBackward0>)

Wjp¯ρ∞ξγ…ʅ“É 9GçMσ′ύàʅχεcχ×|tAΩΩ[Ö;ωæ°±−bü0ληəÜʅχÈ⊢Ām‘Éε≠ZCJîï435Ξψπ>ü’Ιδ…pvΰΨβüYρ∥a4±$µ%*Π%ερæîj£c


In [34]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [52]:
batch_size = 32
for steps in range(10000):

  xb, yb = get_batch('train')

  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

print(loss.item())

2.478816270828247


In [53]:
print(decode(m.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=500)[0].tolist()))



chistheimeng d s emers istithenif and G(bery l tofongrth br + α). bu = st the tand whingreo gion
on e, of ive isinanatond tr . E an F th
athe whondinjuas to f 0
rsubll acondumeth x,” X TR o x.
Se. an, fithereives TE an isavach isw CAR ruathys 1.
tof y to tathibes me wheexprmeamay tlome
as f te f

l th wof m, tong riodusthego t ont thar theconereime s, pon ichin m chetodishin im, as lo the plimathe 81):
catofore elag − st
respollle
vectar at,
cangrisord co alere it
Sunofin oreden d ithe des beme
